# Generated by Django 3.1.3 on 2020-11-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('annict_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mal_anime_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('media', models.CharField(max_length=10)),
                ('official_site_url', models.URLField(default='')),
                ('official_site_url_en', models.URLField(default='')),
                ('season_year', models.IntegerField(default=1900)),
                ('season_name', models.CharField(choices=[('WINTER', '冬'), ('SPRING', '春'), ('SUMMER', '夏'), ('AUTUMN', '秋'), ('OTHER', 'その他')], default='OTHER', max_length=6)),
                ('image_url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annict_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=50)),
                ('name_en', models.CharField(default='', max_length=50)),
                ('role_text', models.CharField(default='', max_length=30)),
                ('sort_number', models.IntegerField(default=9999)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muta.work')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(default='1', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muta.work')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_annict_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=50)),
                ('name_en', models.CharField(default='', max_length=50)),
                ('character_name', models.CharField(default='', max_length=50)),
                ('character_name_en', models.CharField(default='', max_length=50)),
                ('sort_number', models.IntegerField(default='')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muta.work')),
            ],
        ),
    ]
